import os

from dotenv import load_dotenv

load_dotenv()

ICPDAO_MONGODB_ICPDAO_HOST = os.environ['ICPDAO_MONGODB_ICPDAO_HOST']
ICPDAO_GITHUB_APP_ID = os.environ['ICPDAO_GITHUB_APP_ID']
ICPDAO_GITHUB_APP_RSA_PRIVATE_KEY = os.environ['ICPDAO_GITHUB_APP_RSA_PRIVATE_KEY']